'use strict';const assert=require('node:assert/strict');const {ready,run,nav,date,refresh,submit,layout,DATE,PREFIX}=require('./feedback-browser-harness.cjs');
run(async(browser,server)=>{for(const width of [390,768,1024]){const f=await ready(browser,server,width),{page,fixture}=f;try{
 const r=await submit(f,`synthetic journal ${width}`);assert.equal(fixture.entries().length,1);assert.equal(fixture.entries()[0].attempt,1);await refresh(page);assert((await page.locator('.feedback-regeneration').textContent()).includes('受付済み・応答待ち'));
 fixture.publish('running');await refresh(page);assert((await page.locator('.feedback-regeneration').textContent()).includes('処理中'));
 const wrongDate=fixture.publish('succeeded');wrongDate.date='2026-09-05';await refresh(page);assert(!(await page.locator('.feedback-regeneration').textContent()).includes('新版の本文を確認済み'));
 fixture.publish('succeeded',{missing:true});await refresh(page);assert((await page.locator('.feedback-regeneration').textContent()).includes('生成済み・本文未取得'));assert(!(await page.locator('.feedback-regeneration').textContent()).includes('新版の本文を確認済み'));
 fixture.publish('succeeded',{wrongHash:true});await refresh(page);assert(!(await page.locator('.feedback-regeneration').textContent()).includes('新版の本文を確認済み'));
 fixture.publish('succeeded');await refresh(page);assert((await page.locator('.feedback-regeneration').textContent()).includes('新版の本文を確認済み'));
 if(!(await page.locator('.feedback-regeneration > details').evaluate(el=>el.open)))await page.locator('.feedback-regeneration > details > summary').click();await page.locator('[data-action="feedback-version"]:not([data-feedback-version="original"])').click();assert((await page.locator('.feedback-version-body').textContent()).includes('synthetic regenerated '+DATE));assert.equal(await page.locator('.feedback-version-body[data-report-file]').count(),0,'regenerated body never marks canonical read');
 const feedbackBefore=JSON.stringify((await f.state()).feedback);await layout(page,width,'success');await nav(page,'ai-reports');await page.locator('[data-action="ai-report-type"][data-type="feedback"]').click();await page.locator('[data-feedback-report-overlay]').waitFor();await page.locator('[data-action="feedback-report-refresh"]').click();await page.locator('[data-action="feedback-report-date"][data-feedback-date="2026-09-06"]').click();await refresh(page);
 await page.waitForFunction(()=>document.querySelector('.feedback-version-body')?.textContent.includes('synthetic retained request result'));assert((await page.locator('.feedback-version-body').textContent()).includes('synthetic retained request result'));if(!(await page.locator('.feedback-regeneration > details').evaluate(el=>el.open)))await page.locator('.feedback-regeneration > details > summary').click();await page.locator('[data-action="feedback-version"]:not([data-feedback-version="original"])').click();
 await layout(page,width,'ai-success'); await date(page,'2026-09-05');assert((await page.locator('.feedback-regeneration h3').textContent()).startsWith('2026-09-05'));await nav(page,'ai-reports');assert((await page.locator('.feedback-regeneration h3').textContent()).startsWith(DATE));assert((await page.locator('.feedback-version-body').textContent()).includes('synthetic regenerated '+DATE));
 await page.locator('[data-action="feedback-version"][data-feedback-version="original"]').click();assert((await page.locator('.feedback-version-body').textContent()).includes('synthetic retained request result'));assert.equal(fixture.files.get(`taskchute/AIフィードバック_${DATE}.md`),fixture.canonical);
 assert.equal(JSON.stringify((await f.state()).feedback),feedbackBefore,'new version never overwrites canonical state');assert.equal(fixture.entries()[0].requestId,r.requestId);assert.equal(fixture.entries()[0].attempt,1);assert(fixture.calls.some(c=>c.method==='GET'&&c.path===PREFIX+`requests/${r.requestId}.json`),'immutable request actually read back');
 }finally{await f.close();}}}).catch(e=>{console.error(e);process.exitCode=1;});
