'use strict';
// Regular integration gate: real local app, synthetic remote reads only.
// Prepared independently. Browser execution requires an explicit root ownership grant.
const assert=require('assert/strict'),fs=require('fs'),path=require('path');
const helpers=require('./helpers');
const DATE='2026-09-05',PREV='2026-09-04';
const individual=engine=>({version:1,engine:{id:engine,actualModel:'synthetic-'+engine,costUsd:null},generatedAt:'2026-09-06T00:00:00Z',start:{date:PREV,capital:100},nav:{current:engine==='fable'?90:110,dayChangePct:0,totalReturnPct:engine==='fable'?-10:10,series:[{date:PREV,nav:100,n225:null,spx:null},{date:DATE,nav:engine==='fable'?90:110,n225:null,spx:null}]},benchmark:{n225ReturnPct:null,spxReturnPct:null,excessVsN225:null,excessVsSpx:null},cash:50,positions:[],openOrders:[],recentTrades:[],journal:{date:DATE,markdown:'synthetic '+engine}});
function fixtures(){const files=new Map();files.set('dashboard/fund.json',individual('fable'));files.set('dashboard/fund-codex.json',individual('codex'));
files.set('dashboard/fund-comparison.json',{version:1,generatedAt:'2026-09-06T00:00:00Z',status:'ready',startDate:PREV,valuationDate:DATE,series:[{date:PREV,fable:100,codex:100},{date:DATE,fable:90,codex:110}],metrics:{fable:{returnPct:-10,maxDrawdownPct:-10},codex:{returnPct:10,maxDrawdownPct:0}},codexMinusFablePctPoints:20});
for(const [name,body] of [[`FABLE FUND日誌_${DATE}.md`,'FABLE-DAY-5'],[`FABLE FUND日誌_${PREV}.md`,'FABLE-DAY-4'],[`CODEX FUND日誌_${PREV}.md`,'CODEX-DAY-4'],[`朝の投資ブリーフ_${DATE}.md`,'FABLE-BRIEF-DAY-5'],[`朝の投資ブリーフ_CODEX_${DATE}.md`,'CODEX-BRIEF-DAY-5']])files.set(name,body);
files.set('report-index.json',{generatedAt:'2026-09-06T00:00:00Z',files:[...files.keys()].filter(x=>x.endsWith('.md')).map(name=>({name}))});return files;}


async function routes(page,files,control){await page.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.hostname==='localhost')return route.continue();
if(url.hostname!=='api.github.com')return route.abort();assert.equal(req.method(),'GET','unexpected write request');const name=decodeURIComponent(url.pathname).split('/contents/taskchute/')[1];control.requests.push(name||'directory');if(control.hold===name)await new Promise(resolve=>control.release=resolve);if(control.offline)return route.abort('internetdisconnected');const value=files.get(name);try {await route.fulfill({status:value===undefined?404:200,contentType:typeof value==='string'?'text/plain':'application/json',body:typeof value==='string'?value:JSON.stringify(value??{})});} finally {control.settled=(control.settled||0)+1;}});}
async function nav(page,view){let button=page.locator(`[data-action="nav"][data-view="${view}"]:visible`).first();if(!await button.count()){await page.locator('[data-action="nav"][data-view="more"]:visible').first().click();button=page.locator(`[data-action="nav"][data-view="${view}"]:visible`).first();}await button.click();await page.waitForFunction(view=>document.getElementById('app').dataset.view===view,view);}

const {chromium,launchOptions,startServer,randomPort,STATE_KEY}=helpers;
const output=fs.mkdtempSync(path.join(require('os').tmpdir(),'tc-fund-synthetic-'));console.log('Synthetic browser evidence:',output);
async function until(fn){const end=Date.now()+12000;while(!fn()){if(Date.now()>end)throw Error('fixture event timeout');await new Promise(r=>setImmediate(r));}}
(async()=>{
const server=startServer(randomPort());await new Promise(r=>server.listening?r():server.once('listening',r));const origin=`http://localhost:${server.address().port}`;let browser;const results=[];
try{browser=await chromium.launch(launchOptions());
for(const width of [390,768,1024]){const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'});let page;try{
page=await context.newPage();page.setDefaultTimeout(12000);await page.clock.setFixedTime(new Date(2026,8,5,10));const files=fixtures(),control={requests:[],offline:false,hold:null},errors=[];page.on('pageerror',e=>errors.push(e.message));await routes(page,files,control);await page.goto(origin);await page.waitForFunction(k=>!!localStorage.getItem(k),STATE_KEY);
await page.evaluate(({key,date})=>{const s=JSON.parse(localStorage.getItem(key));s.currentView=s.view='journal';s.selectedDate=date;s.journals[date]='SYNTHETIC SAVED JOURNAL';s.settings.autoSync=false;Object.assign(s.settings.github,{token:'synthetic-only',dataOwner:'fixture-owner',dataRepo:'fixture-repo',branch:'main',autoSave:false});localStorage.setItem(key,JSON.stringify(s));},{key:STATE_KEY,date:DATE});await page.reload();await page.locator('[data-action="nav"]:visible').first().waitFor();
await nav(page,'fund');await page.locator('.fund-content').getByText('+20.00ポイント',{exact:false}).waitFor();
for(const engine of ['fable','codex']){await page.locator(`.fund-switches [data-action="fund-select"][data-engine="${engine}"]`).click();await page.locator(`.fund-content[data-fund-selection="${engine}"]`).waitFor();assert.match(await page.locator('.fund-content').innerText(),new RegExp(engine.toUpperCase()));}
await page.locator('.fund-switches [data-action="fund-select"][data-engine="comparison"]').click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:path.join(output,`fund-${width}.png`),fullPage:true});
const before=control.requests.length;await page.locator('[data-action="fund-refresh"]').click();await until(()=>control.requests.length>=before+4);
await page.locator('.fund-switches [data-action="fund-select"][data-engine="fable"]').click();await page.locator(`[data-action="fund-report-open"][data-engine="fable"][data-date="${DATE}"]`).first().click();await page.getByText('FABLE-DAY-5',{exact:true}).waitFor();
await page.locator('[data-action="fund-report-engine"][data-engine="codex"]').click();await page.getByText('この日の日誌はありません',{exact:true}).waitFor();assert.doesNotMatch(await page.locator('[data-fund-report-host]').innerText(),/CODEX-DAY-4/);assert.match(await page.locator('[data-fund-report-host]').innerText(),new RegExp(DATE));
await page.locator('[data-action="fund-report-family"][data-family="brief"]').click();await page.getByText('CODEX-BRIEF-DAY-5',{exact:true}).waitFor();await page.locator('[data-action="fund-report-family"][data-family="journal"]').click();
await page.locator('[data-fund-report-date]').selectOption(PREV);await page.getByText('CODEX-DAY-4',{exact:true}).waitFor();await page.locator('[data-action="fund-report-engine"][data-engine="fable"]').click();await page.getByText('FABLE-DAY-4',{exact:true}).waitFor();
control.offline=true;await context.setOffline(true);await page.locator('[data-action="fund-report-refresh"]').click();await page.getByText(/オフライン|取得に失敗/).first().waitFor();assert.match(await page.locator('[data-fund-report-host]').innerText(),/FABLE-DAY-4/);assert.equal(await page.locator('[data-report-loaded="0"]').count(),1);control.offline=false;await context.setOffline(false);
const types=await page.locator('.ai-report-types').evaluate(host=>{const box=host.getBoundingClientRect();const buttons=[...host.querySelectorAll('button')].map(button=>{const rect=button.getBoundingClientRect();const range=document.createRange();range.selectNodeContents(button);const text=range.getBoundingClientRect();return {label:button.textContent.trim(),left:rect.left,right:rect.right,top:rect.top,bottom:rect.bottom,textLeft:text.left,textRight:text.right,textTop:text.top,textBottom:text.bottom};});return {left:box.left,right:box.right,width:innerWidth,buttons};});assert(types.buttons.length>=4);for(const button of types.buttons){assert(button.left>=types.left-1&&button.right<=types.right+1&&button.right<=types.width+1,'type button outside bar '+button.label);assert(button.textLeft>=button.left-1&&button.textRight<=button.right+1,'type label outside button '+button.label);}for(let i=0;i<types.buttons.length;i++)for(let j=i+1;j<types.buttons.length;j++){const a=types.buttons[i],b=types.buttons[j];assert(!(Math.min(a.textRight,b.textRight)-Math.max(a.textLeft,b.textLeft)>1&&Math.min(a.textBottom,b.textBottom)-Math.max(a.textTop,b.textTop)>1),'overlapping type labels');}fs.writeFileSync(path.join(output,`report-types-${width}.json`),JSON.stringify(types,null,2));
await page.screenshot({path:path.join(output,`report-${width}.png`),fullPage:true});
// An old read must not reappear after connection invalidation, including a focused date SELECT.
control.hold=`FABLE FUND日誌_${PREV}.md`;await page.locator('[data-action="fund-report-refresh"]').click();await until(()=>!!control.release);await page.locator('[data-fund-report-date]').focus();await page.evaluate(async()=>{const {state}=await import('/src/state/store.js');state.settings.github.dataRepo='fixture-next';const fund=await import('/src/features/fund.js');fund.invalidateFundConnection();});assert.doesNotMatch(await page.locator('[data-fund-report-host]').innerText(),/FABLE-DAY-4/);const settled=control.settled||0;control.hold=null;control.release();control.release=null;await until(()=>control.settled>settled);await page.evaluate(()=>new Promise(requestAnimationFrame));assert.doesNotMatch(await page.locator('[data-fund-report-host]').innerText(),/FABLE-DAY-4/);
// Same-date MONEY refresh may update its own surface during IME, never the editor.
await nav(page,'journal');await page.locator('[data-journal-section="journal"]').evaluate(e=>e.open=true);const textarea=page.locator(`[data-journal-date="${DATE}"]`);await textarea.waitFor();const handle=await textarea.elementHandle();await textarea.focus();await textarea.evaluate(e=>{e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true}));e.value='SYNTHETIC IME DRAFT';e.dispatchEvent(new InputEvent('input',{bubbles:true,data:'DRAFT',isComposing:true}));});
await page.evaluate(async()=>{const fund=await import('/src/features/fund.js');fund.invalidateFundConnection();fund.hydrateFundSurfaces();});await page.locator('[data-fund-money]').getByText('FABLE-DAY-5',{exact:true}).waitFor();assert.equal(await handle.evaluate(e=>e.isConnected&&document.activeElement===e&&e.value==='SYNTHETIC IME DRAFT'),true);await textarea.evaluate(e=>e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true})));await textarea.blur();
await page.locator('[data-journal-section="money"]').evaluate(e=>e.open=true);const moneyButton=page.locator('[data-fund-money] [data-action="fund-report-open"][data-engine="fable"]');await moneyButton.scrollIntoViewIfNeeded();const scroll=await page.evaluate(()=>[document.scrollingElement,document.getElementById('app'),document.getElementById('main')].map(e=>e?.scrollTop||0));assert(scroll[0]>0,'document scroll fixture must exercise a nonzero position');await moneyButton.click();await page.locator('[data-action="fund-report-back"]').click();await page.waitForSelector(`[data-journal-date="${DATE}"]`);assert.equal(await textarea.inputValue(),'SYNTHETIC IME DRAFT');assert.deepEqual(await page.evaluate(()=>[document.scrollingElement,document.getElementById('app'),document.getElementById('main')].map(e=>e?.scrollTop||0)),scroll);assert.deepEqual(errors,[]);results.push({width,pass:true,requests:control.requests.length});
}catch(error){if(page){await page.screenshot({path:path.join(output,'failure-'+width+'.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(output,'failure-'+width+'.html'),await page.content());}throw error;}finally{await context.close();}}
console.log(JSON.stringify(results));}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(results,null,2));}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});







