const assert = require('node:assert/strict');
const { chromium, launchOptions, startServer, blockGithubApiByDefault, passGithubGate, randomPort, STATE_KEY } = require('./helpers');
let assertions = 0;
const equal = (actual, expected, message) => { assert.deepEqual(actual, expected, message); assertions++; console.log('PASS', message); };
const ok = (value, message) => { assert.ok(value, message); assertions++; console.log('PASS', message); };

(async () => {
  const server = startServer(randomPort()), browser = await chromium.launch(launchOptions());
  const context = await browser.newContext({ serviceWorkers: 'block', timezoneId: 'Asia/Tokyo', viewport: { width: 1024, height: 900 } });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.setDefaultTimeout(10000);
  const day = '2026-10-03', tomorrow = '2026-10-04';
  const live = () => page.evaluate(async () => JSON.parse(JSON.stringify((await import('/src/state/store.js')).state)));
  const stored = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), STATE_KEY);
  const card = id => page.locator(`.routine-card[data-rule-id="${id}"]`);
  const click = (action, id) => page.locator(`[data-action="routine-${action}"]${id === undefined ? '' : `[data-rule-id="${id}"]`}`).click();
  const rule = (id, startTime, endTime, extra = {}) => ({ id, title: id, startTime, endTime, category: '生活', kind: 'daily',
    anchorDate: day, days: [], exceptionDates: [], deleted: false, updatedAt: '2026-10-01T00:00:00', ...extra });
  try {
    await blockGithubApiByDefault(page);
    await page.clock.install({ time: new Date(2026, 9, 3, 12, 0) });
    await page.goto(`http://localhost:${server.address().port}`);
    await page.waitForFunction(key => !!localStorage.getItem(key), STATE_KEY);
    await passGithubGate(page);
    await page.evaluate(({ key, day, tomorrow, rules }) => {
      const s = JSON.parse(localStorage.getItem(key));
      Object.assign(s, { recurrences: rules, blocks: [{ id: `rec_morning_${tomorrow}`, title: 'morning', date: tomorrow,
        recurrenceGroupId: 'morning', actualStartAt: `${tomorrow}T06:00:00`, plannedStartAt: `${tomorrow}T06:00:00`,
        plannedEndAt: `${tomorrow}T06:25:00`, completed: false, deleted: false, category: '生活' }],
        currentView: 'more', selectedDate: day, tasks: [], projects: [], singleSchedules: [], declarations: [] });
      Object.assign(s.settings, { autoSync: false, lastOpenedDate: day });
      s.settings.github.autoSave = false; s.pomodoro.running = false;
      localStorage.setItem(key, JSON.stringify(s));
    }, { key: STATE_KEY, day, tomorrow, rules: [rule('night', '23:30', '00:15'), rule('weekly', '08:00', '08:30', { kind: 'weekly', days: [1, 3] }),
      rule('morning', '06:00', '06:25'), rule('untimed', '', ''), rule('deleted', '01:00', '02:00', { deleted: true })] });
    await page.reload();
    await page.locator('#sidebar [data-action="nav"][data-view="routine"]').click();
    await page.locator('#app[data-view="routine"] .routine-card').first().waitFor();
    equal(await page.locator('.routine-card').evaluateAll(nodes => nodes.map(node => node.dataset.ruleId)), ['morning', 'weekly', 'night', 'untimed'], '有効ルールを時刻順、時刻なしは末尾');
    ok((await card('morning').innerText()).includes('見積 25 分'), '毎日06:00〜06:25は25分');
    ok((await card('weekly').innerText()).includes('曜日 月・水'), '曜日ラベル');
    ok((await card('night').innerText()).includes('見積 45 分'), '日跨ぎ見積45分');
    ok((await card('untimed').innerText()).includes('見積 —'), '時刻なしの見積');
    equal(await page.locator('.routine-cards').evaluate(node => getComputedStyle(node).gridTemplateColumns.split(' ').length), 2, 'PCは2列');
    await page.setViewportSize({ width: 375, height: 900 });
    equal(await page.locator('#bottomNav button').count(), 6, 'モバイル下部ナビ6枠');
    await page.locator('#bottomNav [data-view="more"]').click();
    equal(await page.locator('.more-tower-grid [data-view="routine"]').innerText(), '↻ルーティン\n計画', 'その他にルーティン');
    await page.locator('.more-tower-grid [data-view="routine"]').click();
    equal(await page.locator('.routine-cards').evaluate(node => getComputedStyle(node).gridTemplateColumns.split(' ').length), 1, '375pxは1列');
    ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '375pxで横はみ出しなし');
    await click('new');
    equal(await page.locator('[name="kind"]').inputValue(), 'daily', '新規は毎日');
    equal(await page.locator('[name="startTime"]').inputValue(), '', '新規時刻は空');
    await page.locator('[name="title"]').fill('夜の読書');
    await page.locator('[name="startTime"]').fill('21:00');
    await page.locator('[name="endTime"]').fill('21:30');
    await page.locator('[name="category"]').fill('読書');
    await page.locator('[name="kind"]').selectOption('weekly');
    ok(await page.locator('.routine-form input, .routine-form select').evaluateAll(nodes => nodes.every(node => parseFloat(getComputedStyle(node).fontSize) >= 16 && node.getBoundingClientRect().height >= 44)), '入力16px以上・44px以上');
    await page.locator('[name="kind"]').selectOption('daily');
    equal(await page.locator('input[type="time"]').evaluateAll(nodes => nodes.map(node => node.step)), ['300', '300'], '時刻はネイティブ5分刻み');
    const beforeCount = (await live()).recurrences.length;
    await click('save', '');
    let s = await live(), added = s.recurrences.find(item => item.title === '夜の読書');
    equal(s.recurrences.length, beforeCount + 1, 'ルール1件追加');
    equal([added.kind, added.startTime, added.endTime, added.category], ['daily', '21:00', '21:30', '読書'], '新規ルールの保存項目');
    ok(s.blocks.some(item => item.id === `rec_${added.id}_${day}`), '今日の実体を生成');
    await page.reload();
    await page.locator('#app[data-view="routine"] .routine-card').first().waitFor();
    s = await live();
    ok(s.recurrences.some(item => item.id === added.id), '再読込後もルール保持');
    ok(s.blocks.some(item => item.id === `rec_${added.id}_${day}`), '再読込後も実体保持');
    const actualBefore = s.blocks.find(item => item.id === `rec_morning_${tomorrow}`);
    await click('edit', 'morning');
    await page.locator('[name="startTime"]').fill('07:00');
    await page.locator('[name="title"]').fill('朝の準備');
    await click('end', 'night');
    equal(await page.locator('[name="title"]').inputValue(), '朝の準備', '別カードの確認表示でも入力保持');
    await click('end-confirm', 'night');
    equal(await page.locator('[name="startTime"]').inputValue(), '07:00', '別カード終了の再描画後も下書き保持');
    await page.locator('[name="title"]').press('End');
    equal(await page.locator('[name="title"]').inputValue(), '朝の準備', '入力後に他ボタン操作なしでも保持');
    await click('save', 'morning');
    s = await live();
    const edited = s.recurrences.find(item => item.id === 'morning');
    equal(edited.title, '朝の準備', '同じidで題名編集');
    ok(edited.updatedAt > '2026-10-01T00:00:00', 'updatedAt更新');
    ok(s.blocks.find(item => item.id === `rec_morning_${day}`).plannedStartAt.startsWith(`${day}T07:00`), '今日の未編集実体を新時刻に更新');
    equal(s.blocks.find(item => item.id === `rec_morning_${day}`).title, '朝の準備', '題名変更で未編集実体を取り残さない');
    equal(s.blocks.find(item => item.id === actualBefore.id), actualBefore, '編集時も実行済み実体は不変');
    await click('end', 'morning');
    ok(!(await live()).recurrences.find(item => item.id === 'morning').deleted, '終了1段目は未確定');
    equal(await card('morning').locator('[data-action="routine-end-confirm"]').innerText(), '本当に終了', '終了確認ボタン');
    await click('end-confirm', 'morning');
    s = await stored();
    equal(s.recurrences.find(item => item.id === 'morning').deleted, true, '終了墓標を保存');
    ok(!s.blocks.some(item => item.recurrenceGroupId === 'morning' && item.date >= day && !item.actualStartAt), '終了で今日以降の未編集実体を削除');
    equal(s.blocks.find(item => item.id === actualBefore.id), actualBefore, '終了時も実行済みを保持');
    await click('new');
    await page.locator('[name="title"]').fill('夜の読書');
    await page.locator('[name="startTime"]').fill('21:00');
    const duplicateCount = (await live()).recurrences.length;
    await click('save', '');
    equal((await live()).recurrences.length, duplicateCount, '重複ルールは増えない');
    ok(await page.getByText('「夜の読書」の繰り返しルールは既にあるため作成しませんでした', { exact: true }).isVisible(), '既存重複検知のトースト');
    equal(await page.locator('[name="title"]').inputValue(), '夜の読書', '重複拒否でも入力保持');
    await click('cancel');
    await click('edit', 'weekly');
    const beforeDuplicateEdit = await live(), storedBeforeDuplicateEdit = await stored();
    await page.locator('[name="title"]').fill('夜の読書');
    await page.locator('[name="startTime"]').fill('21:00');
    await click('save', 'weekly');
    equal((await live()).recurrences, beforeDuplicateEdit.recurrences, '編集重複拒否でルールは元の値のまま');
    equal((await live()).blocks, beforeDuplicateEdit.blocks, '編集重複拒否で実体を変更しない');
    equal(await stored(), storedBeforeDuplicateEdit, '編集重複拒否で保存しない');
    ok(await page.getByText('「夜の読書」の繰り返しルールは既にあるため作成しませんでした', { exact: true }).isVisible(), '編集重複も新規と同じトースト');
    equal(await page.locator('[name="title"]').inputValue(), '夜の読書', '編集重複拒否でも入力保持');
    await click('cancel');
    await click('edit', 'weekly');
    await page.locator('[name="category"]').fill('変更後の分類');
    await click('save', 'weekly');
    const selfSaved = (await stored()).recurrences.find(item => item.id === 'weekly');
    equal([selfSaved.title, selfSaved.startTime, selfSaved.category], ['weekly', '08:00', '変更後の分類'], '自分自身の題名・時刻を変えない保存は通る');
    ok(await card('weekly').locator('.routine-form').count() === 0, '自己重複で拒否されず編集を終了');
    await click('edit', 'weekly');
    await page.locator('[name="kind"]').selectOption('weekend');
    ok(await page.locator('.routine-days').isHidden(), '週末では曜日入力非表示');
    await click('save', 'weekly');
    equal((await live()).recurrences.find(item => item.id === 'weekly').days, [0, 6], '週末はweekly+日土');
    await click('edit', 'weekly');
    await page.locator('[name="kind"]').selectOption('weekly');
    await page.locator('[name="day"][value="0"]').uncheck();
    await page.locator('[name="day"][value="6"]').uncheck();
    await page.locator('[name="day"][value="1"]').check();
    await page.locator('[name="day"][value="3"]').check();
    await click('save', 'weekly');
    equal((await live()).recurrences.find(item => item.id === 'weekly').days, [1, 3], '曜日編集を保存');
    await click('edit', 'weekly');
    await page.locator('[name="title"]').fill('取り消す変更');
    await click('cancel');
    equal((await live()).recurrences.find(item => item.id === 'weekly').title, 'weekly', 'やめるで変更破棄');
    equal(errors, [], 'ブラウザ例外なし');
    console.log(`routine-view: ${assertions} assertions passed`);
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
