const assert = require('node:assert/strict');
const { chromium, launchOptions, startServer, blockGithubApiByDefault, passGithubGate, randomPort, STATE_KEY } = require('./helpers');
let assertions = 0;
const equal = (actual, expected, message) => { assert.deepEqual(actual, expected, message); assertions++; console.log('PASS', message); };
const ok = (value, message) => { assert.ok(value, message); assertions++; console.log('PASS', message); };

(async () => {
  const server = startServer(randomPort()), browser = await chromium.launch(launchOptions());
  const context = await browser.newContext({ serviceWorkers: 'block', timezoneId: 'Asia/Tokyo', viewport: { width: 1024, height: 900 } });
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.setDefaultTimeout(10000);
  const day = '2026-10-03', tomorrow = '2026-10-04';
  const live = () => page.evaluate(async () => JSON.parse(JSON.stringify((await import('/src/state/store.js')).state)));
  const stored = () => page.evaluate(key => JSON.parse(localStorage.getItem(key)), STATE_KEY);
  const card = id => page.locator(`.routine-card[data-rule-id="${id}"]`);
  const click = (action, id) => page.locator(`[data-action="routine-${action}"]${id === undefined ? '' : `[data-rule-id="${id}"]`}`).click();
  const rule = (id, startTime, endTime, extra = {}) => ({ id, title: id, startTime, endTime, category: '生活', kind: 'daily',
    anchorDate: day, days: [], exceptionDates: [], deleted: false, updatedAt: '2026-10-01T00:00:00', ...extra });
  try {
    await blockGithubApiByDefault(page);
    await page.clock.install({ time: new Date(2026, 9, 3, 12, 0) });
    await page.goto(`http://localhost:${server.address().port}`);
    await page.waitForFunction(key => !!localStorage.getItem(key), STATE_KEY);
    await passGithubGate(page);
    await page.evaluate(({ key, day, tomorrow, rules }) => {
      const s = JSON.parse(localStorage.getItem(key));
      Object.assign(s, { recurrences: rules, blocks: [{ id: `rec_morning_${tomorrow}`, title: 'morning', date: tomorrow,
        recurrenceGroupId: 'morning', actualStartAt: `${tomorrow}T06:00:00`, plannedStartAt: `${tomorrow}T06:00:00`,
        plannedEndAt: `${tomorrow}T06:25:00`, completed: false, deleted: false, category: '生活' }],
        currentView: 'more', selectedDate: day, tasks: [], projects: [], singleSchedules: [], declarations: [] });
      Object.assign(s.settings, { autoSync: false, lastOpenedDate: day });
      s.settings.github.autoSave = false; s.pomodoro.running = false;
      localStorage.setItem(key, JSON.stringify(s));
    }, { key: STATE_KEY, day, tomorrow, rules: [rule('night', '23:30', '00:15'), rule('weekly', '08:00', '08:30', { kind: 'weekly', days: [1, 3] }),
      rule('morning', '06:00', '06:25'), rule('untimed', '', ''), rule('deleted', '01:00', '02:00', { deleted: true })] });
    await page.reload();
    await page.locator('#sidebar [data-action="nav"][data-view="routine"]').click();
    await page.locator('#app[data-view="routine"] .routine-card').first().waitFor();
    equal(await page.getByRole('heading', { name: 'ルーティン', exact: true }).count(), 1, 'ルーティン見出しは1つ');
    equal(await page.locator('.routine-card').evaluateAll(nodes => nodes.map(node => node.dataset.ruleId)), ['morning', 'weekly', 'night', 'untimed'], '有効ルールを時刻順、時刻なしは末尾');
    ok((await card('morning').innerText()).includes('見積 30 分'), 'B2-71: 実績なしは共通見積30分');
    ok((await card('weekly').innerText()).includes('曜日 月・水'), '曜日ラベル');
    ok((await card('night').innerText()).includes('見積 30 分'), 'B2-71: 日跨ぎでも共通見積30分');
    ok((await card('untimed').innerText()).includes('見積 30 分'), 'B2-71: 時刻なしも共通見積30分');
    equal(await page.locator('.routine-cards').evaluate(node => getComputedStyle(node).gridTemplateColumns.split(' ').length), 2, 'PCは2列');
    await page.setViewportSize({ width: 375, height: 900 });
    equal(await page.locator('#bottomNav button').count(), 6, 'モバイル下部ナビ6枠');
    await page.locator('#bottomNav [data-view="more"]').click();
    equal(await page.locator('.more-tower-grid [data-view="routine"]').innerText(), '↻ルーティン\n計画', 'その他にルーティン');
    await page.locator('.more-tower-grid [data-view="routine"]').click();
    equal(await page.locator('.routine-cards').evaluate(node => getComputedStyle(node).gridTemplateColumns.split(' ').length), 1, '375pxは1列');
    ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), '375pxで横はみ出しなし');
    await click('new');
    equal(await page.locator('[name="kind"]').inputValue(), 'daily', '新規は毎日');
    equal(await page.locator('[name="startTime"]').inputValue(), '', '新規時刻は空');
    await page.locator('[name="title"]').fill('夜の読書');
    await page.locator('[name="startTime"]').fill('21:00');
    await page.locator('[name="endTime"]').fill('21:30');
    await page.locator('[name="category"]').fill('読書');
    await page.locator('[name="kind"]').selectOption('weekly');
    ok(await page.locator('.routine-form input, .routine-form select').evaluateAll(nodes => nodes.every(node => parseFloat(getComputedStyle(node).fontSize) >= 16 && node.getBoundingClientRect().height >= 44)), '入力16px以上・44px以上');
    await page.locator('[name="kind"]').selectOption('daily');
    equal(await page.locator('input[type="time"]').evaluateAll(nodes => nodes.map(node => node.step)), ['300', '300'], '時刻はネイティブ5分刻み');
    const beforeCount = (await live()).recurrences.length;
    await click('save', '');
    let s = await live(), added = s.recurrences.find(item => item.title === '夜の読書');
    equal(s.recurrences.length, beforeCount + 1, 'ルール1件追加');
    equal([added.kind, added.startTime, added.endTime, added.category], ['daily', '21:00', '21:30', '読書'], '新規ルールの保存項目');
    equal(Object.hasOwn((await stored()).recurrences.find(item => item.id === added.id), 'days'), false, '非weeklyの新規保存はdaysキー無し');
    ok(s.blocks.some(item => item.id === `rec_${added.id}_${day}`), '今日の実体を生成');
    await page.reload();
    await page.locator('#app[data-view="routine"] .routine-card').first().waitFor();
    s = await live();
    ok(s.recurrences.some(item => item.id === added.id), '再読込後もルール保持');
    ok(s.blocks.some(item => item.id === `rec_${added.id}_${day}`), '再読込後も実体保持');
    const actualBefore = s.blocks.find(item => item.id === `rec_morning_${tomorrow}`);
    await click('edit', 'morning');
    await page.locator('[name="startTime"]').fill('07:00');
    await page.locator('[name="title"]').fill('朝の準備');
    await click('end', 'night');
    equal(await page.locator('[name="title"]').inputValue(), '朝の準備', '別カードの確認表示でも入力保持');
    await page.clock.fastForward(600);
    await click('end-confirm', 'night');
    equal(await page.locator('[name="startTime"]').inputValue(), '07:00', '別カード終了の再描画後も下書き保持');
    await page.locator('[name="title"]').press('End');
    equal(await page.locator('[name="title"]').inputValue(), '朝の準備', '入力後に他ボタン操作なしでも保持');
    await click('save', 'morning');
    s = await live();
    const edited = s.recurrences.find(item => item.id === 'morning');
    equal(edited.title, '朝の準備', '同じidで題名編集');
    ok(edited.updatedAt > '2026-10-01T00:00:00', 'updatedAt更新');
    ok(s.blocks.find(item => item.id === `rec_morning_${day}`).plannedStartAt.startsWith(`${day}T07:00`), '今日の未編集実体を新時刻に更新');
    equal(s.blocks.find(item => item.id === `rec_morning_${day}`).title, '朝の準備', '題名変更で未編集実体を取り残さない');
    equal(s.blocks.find(item => item.id === actualBefore.id), actualBefore, '編集時も実行済み実体は不変');
    await click('end', 'morning');
    ok(!(await live()).recurrences.find(item => item.id === 'morning').deleted, '終了1段目は未確定');
    equal(await card('morning').locator('[data-action="routine-end-confirm"]').innerText(), '本当に終了', '終了確認ボタン');
    await page.clock.fastForward(600);
    await click('end-confirm', 'morning');
    s = await stored();
    equal(s.recurrences.find(item => item.id === 'morning').deleted, true, '終了墓標を保存');
    ok(!s.blocks.some(item => item.recurrenceGroupId === 'morning' && item.date >= day && !item.actualStartAt), '終了で今日以降の未編集実体を削除');
    equal(s.blocks.find(item => item.id === actualBefore.id), actualBefore, '終了時も実行済みを保持');
    await click('new');
    await page.locator('[name="title"]').fill('夜の読書');
    await page.locator('[name="startTime"]').fill('21:00');
    const duplicateCount = (await live()).recurrences.length;
    await click('save', '');
    equal((await live()).recurrences.length, duplicateCount, '重複ルールは増えない');
    ok(await page.getByText('「夜の読書」の繰り返しルールは既にあるため作成しませんでした', { exact: true }).isVisible(), '既存重複検知のトースト');
    equal(await page.locator('[name="title"]').inputValue(), '夜の読書', '重複拒否でも入力保持');
    await click('cancel');
    await click('edit', 'weekly');
    const beforeDuplicateEdit = await live(), storedBeforeDuplicateEdit = await stored();
    await page.locator('[name="title"]').fill('夜の読書');
    await page.locator('[name="startTime"]').fill('21:00');
    await click('save', 'weekly');
    equal((await live()).recurrences, beforeDuplicateEdit.recurrences, '編集重複拒否でルールは元の値のまま');
    equal((await live()).blocks, beforeDuplicateEdit.blocks, '編集重複拒否で実体を変更しない');
    equal(await stored(), storedBeforeDuplicateEdit, '編集重複拒否で保存しない');
    ok(await page.getByText('「夜の読書」の繰り返しルールは既にあるため作成しませんでした', { exact: true }).isVisible(), '編集重複も新規と同じトースト');
    equal(await page.locator('[name="title"]').inputValue(), '夜の読書', '編集重複拒否でも入力保持');
    await click('cancel');
    await click('edit', 'weekly');
    await page.locator('[name="category"]').fill('変更後の分類');
    await click('save', 'weekly');
    const selfSaved = (await stored()).recurrences.find(item => item.id === 'weekly');
    equal([selfSaved.title, selfSaved.startTime, selfSaved.category], ['weekly', '08:00', '変更後の分類'], '自分自身の題名・時刻を変えない保存は通る');
    ok(await card('weekly').locator('.routine-form').count() === 0, '自己重複で拒否されず編集を終了');
    await click('edit', 'weekly');
    await page.locator('[name="kind"]').selectOption('weekend');
    ok(await page.locator('.routine-days').isHidden(), '週末では曜日入力非表示');
    await click('save', 'weekly');
    equal((await live()).recurrences.find(item => item.id === 'weekly').days, [0, 6], '週末はweekly+日土');
    await click('edit', 'weekly');
    await page.locator('[name="kind"]').selectOption('weekly');
    await page.locator('[name="day"][value="0"]').uncheck();
    await page.locator('[name="day"][value="6"]').uncheck();
    await page.locator('[name="day"][value="1"]').check();
    await page.locator('[name="day"][value="3"]').check();
    await click('save', 'weekly');
    equal((await live()).recurrences.find(item => item.id === 'weekly').days, [1, 3], '曜日編集を保存');
    await click('edit', 'weekly');
    await page.locator('[name="title"]').fill('取り消す変更');
    await click('cancel');
    equal((await live()).recurrences.find(item => item.id === 'weekly').title, 'weekly', 'やめるで変更破棄');
    for (const kind of ['daily', 'weekdays', 'monthly']) {
      await click('edit', 'weekly');
      await page.locator('[name="kind"]').selectOption(kind);
      await click('save', 'weekly');
      equal(Object.hasOwn((await stored()).recurrences.find(item => item.id === 'weekly'), 'days'), false, `${kind}: 非weeklyへの編集でもdaysを除去`);
    }
    // 時刻だけ編集した実体はルール編集と終了の両方から守る。
    const timeEdits = await page.evaluate(async ({ id, day }) => {
      const s = (await import('/src/state/store.js')).state;
      const { makeRecurrenceInstance } = await import('/src/core/recurrence.js');
      const r = s.recurrences.find(item => item.id === id);
      const start = makeRecurrenceInstance(r, day), end = makeRecurrenceInstance(r, '2026-10-04');
      start.plannedStartAt = `${day}T20:55:00`;
      end.plannedEndAt = '2026-10-04T21:40:00';
      s.blocks = s.blocks.filter(b => ![start.id, end.id].includes(b.id));
      s.blocks.push(start, end);
      return [start, end];
    }, { id: added.id, day });
    await click('edit', added.id);
    await page.locator('[name="category"]').fill('読書分類を編集');
    await click('save', added.id);
    equal((await stored()).blocks.filter(b => timeEdits.some(item => item.id === b.id)), timeEdits, 'L-time-touch: 開始のみ・終了のみの変更をルール編集時に保持');
    await click('end', added.id);
    await page.clock.fastForward(600);
    await click('end-confirm', added.id);
    equal((await stored()).blocks.filter(b => timeEdits.some(item => item.id === b.id)), timeEdits, 'L-time-touch: 時刻だけ変えた実体をルール終了時も保持');
    await click('new');
    await page.locator('[name="title"]').fill('朝の水');
    await page.locator('[name="startTime"]').fill('07:00');
    await page.locator('[name="category"]').fill('   ');
    await click('save', '');
    const water = (await stored()).recurrences.find(r => r.title === '朝の水');
    equal(water.category, 'ルーティン', 'B2-69: 空欄はルーティンとして保存');
    await page.clock.setSystemTime(new Date(2026, 9, 4, 12));
    await page.evaluate(async tomorrow => {
      const s = (await import('/src/state/store.js')).state;
      s.selectedDate = tomorrow;
      document.querySelector('.routine-view').insertAdjacentHTML('afterend', (await import('/src/features/now-view.js')).renderNowView());
    }, tomorrow);
    equal(await page.locator(`.now-routine [data-action="now-routine-complete"][data-id="rec_${water.id}_${tomorrow}"]`).count(), 1, 'B2-69: 翌日の実体がいまのルーティン枠に出る');
    await page.clock.setSystemTime(new Date(2026, 9, 3, 12));
    await page.evaluate(async day => { (await import('/src/state/store.js')).state.selectedDate = day; document.querySelector('.now-view').remove(); }, day);
    const customized = await page.evaluate(async id => {
      const s = (await import('/src/state/store.js')).state;
      const blocks = s.blocks.filter(b => b.recurrenceGroupId === id);
      blocks[0].plannedStartAt = `${blocks[0].date}T07:45:00`;
      blocks[1].estimateMin = 47;
      blocks[2].orderIndex = 3;
      return blocks;
    }, water.id);
    await click('edit', water.id);
    await click('save', water.id);
    equal((await live()).blocks.filter(b => b.recurrenceGroupId === water.id), customized, 'B2-70: 無変更保存で時刻・見積・順番・idをすべて保持');
    await click('edit', water.id);
    await page.locator('[name="category"]').fill('');
    await click('save', water.id);
    equal((await stored()).recurrences.find(r => r.id === water.id).category, '', 'B2-69補足: 既存ルールのカテゴリは空に変更できる');
    for (const taskId of ['', 'twy-empty-category']) {
      const before = await page.evaluate(async ({ id, taskId }) => {
        const s = (await import('/src/state/store.js')).state;
        s.recurrences.find(r => r.id === id).taskId = taskId;
        if (taskId) s.tasks.push({ id: taskId, twyPlan: { week: 1 } });
        return JSON.parse(JSON.stringify({ recurrences: s.recurrences, blocks: s.blocks }));
      }, { id: water.id, taskId });
      const persisted = await stored();
      await click('edit', water.id);
      equal(await page.locator('[name="category"]').inputValue(), '', 'B2-69補足: 既存の空カテゴリを復元');
      await click('save', water.id);
      const after = await live();
      equal({ recurrences: after.recurrences, blocks: after.blocks }, before, `B2-69補足: ${taskId || '通常'}の無変更保存でルール・全実体を保持`);
      equal(await stored(), persisted, 'B2-69補足: 無変更保存は永続化もしない');
      equal(await card(water.id).locator('.routine-form').count(), 0, 'B2-69補足: 無変更保存で編集を終了');
    }
    await click('edit', water.id);
    await page.locator('[name="category"]').fill('朝の習慣');
    await click('save', water.id);
    equal((await stored()).recurrences.find(r => r.id === water.id).category, '朝の習慣', 'B2-69補足: 既存の空カテゴリに入力した値を保存');
    await page.evaluate(async ({ id, day }) => {
      const s = (await import('/src/state/store.js')).state;
      const r = s.recurrences.find(r => r.id === id);
      r.taskId = 'twy-task'; s.tasks.push({ id: 'twy-task', twyPlan: { week: 1 } });
      s.blocks.find(b => b.recurrenceGroupId === id && b.date === day).estimateMin = 47;
      s.blocks.push({ id: 'past-night', recurrenceGroupId: 'night', completed: true, actualStartAt: '2026-10-01T23:30:00', actualEndAt: '2026-10-01T23:50:00' });
      s.recurrences.find(r => r.id === 'night').deleted = false;
      document.querySelector('.routine-view').outerHTML = (await import('/src/features/routine-view.js')).renderRoutineView();
    }, { id: water.id, day });
    ok((await card(water.id).innerText()).includes('見積 47 分'), 'B2-71: 今日の実体の明示見積を共通関数で表示');
    ok((await card('night').innerText()).includes('見積 20 分'), 'B2-71: 実体なしでもルールの過去実績中央値を表示');
    ok((await card(water.id).innerText()).includes('12週'), 'B2-72: twyPlanを持つタスク由来に12週表示');
    ok(!(await card('night').innerText()).includes('12週'), 'B2-72: 通常ルールには12週表示なし');
    await click('new');
    await page.locator('[name="title"]').fill('月末確認');
    await page.locator('[name="kind"]').selectOption('monthly');
    await page.locator('[name="monthDay"]').fill('31');
    ok(await page.locator('[name="monthDay"]').evaluate(n => n.type === 'number' && n.min === '1' && n.max === '31' && parseFloat(getComputedStyle(n).fontSize) >= 16), 'B2-73: 月の日は1〜31の数値入力・16px以上');
    await click('save', '');
    const monthly = (await stored()).recurrences.find(r => r.title === '月末確認');
    equal(monthly.anchorDate, '2026-10-31', 'B2-73: 毎月の日をanchorDateへ保存');
    ok((await card(monthly.id).innerText()).includes('毎月 31 日'), 'B2-73: 毎月の日をカードに表示');
    await click('edit', monthly.id);
    equal(await page.locator('[name="monthDay"]').inputValue(), '31', 'B2-73: 既存ルールの日を復元');
    await page.locator('[name="monthDay"]').fill('15');
    await click('save', monthly.id);
    equal((await stored()).recurrences.find(r => r.id === monthly.id).anchorDate, '2026-10-15', 'B2-73: 毎月の日を編集');
    for (const anchorDate of ['', undefined]) {
      await page.evaluate(async ({ id, anchorDate }) => {
        const s = (await import('/src/state/store.js')).state;
        const r = s.recurrences.find(r => r.id === id);
        if (anchorDate === undefined) delete r.anchorDate; else r.anchorDate = anchorDate;
        document.querySelector('.routine-view').outerHTML = (await import('/src/features/routine-view.js')).renderRoutineView();
      }, { id: monthly.id, anchorDate });
      equal(await card(monthly.id).locator('p').first().innerText(), '毎月', 'B2-73補足: anchorDateが空・未定義でも一覧を表示');
      await click('edit', monthly.id);
      equal(await page.locator('[name="monthDay"]').inputValue(), '3', 'B2-73補足: anchorDate欠落時の日は今日');
      await click('save', monthly.id);
      equal((await stored()).recurrences.find(r => r.id === monthly.id).anchorDate, day, 'B2-73補足: 無操作保存でも欠落anchorDateを作成');
    }
    await page.evaluate(async () => {
      const s = (await import('/src/state/store.js')).state;
      Object.assign(s.recurrences.find(r => r.id === 'weekly'), { kind: 'weekly', days: [] });
      document.querySelector('.routine-view').outerHTML = (await import('/src/features/routine-view.js')).renderRoutineView();
    });
    ok((await card('weekly').innerText()).includes('曜日未設定'), 'B2-74: 曜日ゼロのカード表示');
    await click('edit', 'weekly');
    const beforeEmptyDays = await live();
    await click('save', 'weekly');
    ok(await page.getByText('曜日を 1 つ以上選んでください', { exact: true }).isVisible(), 'B2-74: 曜日ゼロの保存エラー');
    equal((await live()).recurrences, beforeEmptyDays.recurrences, 'B2-74: 保存拒否でルール不変');
    await click('cancel');
    await page.clock.pauseAt(new Date(2026, 9, 3, 13));
    await card(water.id).locator('[data-action="routine-end"]').scrollIntoViewIfNeeded();
    const endBox = await card(water.id).locator('[data-action="routine-end"]').boundingBox();
    await page.mouse.click(endBox.x + 15, endBox.y + endBox.height / 2);
    await page.mouse.click(endBox.x + 15, endBox.y + endBox.height / 2);
    equal(await card(water.id).locator('[data-action="routine-end-confirm"]').count(), 1, 'B2-75: 同じ座標の連打後も確認モード');
    ok(!(await live()).recurrences.find(r => r.id === water.id).deleted, 'B2-75: 同じ座標の素早い2回押しでは削除しない');
    await page.clock.fastForward(599);
    await click('end-confirm', water.id);
    ok(!(await live()).recurrences.find(r => r.id === water.id).deleted, 'B2-75: 599msでは削除しない');
    await page.clock.fastForward(1);
    await click('end-confirm', water.id);
    equal((await stored()).recurrences.find(r => r.id === water.id).deleted, true, 'B2-75: 600ms後の確認で削除');
    equal(errors, [], 'ブラウザ例外なし');
    console.log(`routine-view: ${assertions} assertions passed`);
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
})().catch(error => { console.error(error); process.exitCode = 1; });
