"use strict";

const fs = require("fs");
const path = require("path");

const repoRoot = path.resolve(__dirname, "..");
const args = process.argv.slice(2);
const manifestArg = args.find((arg) => !arg.startsWith("--"));
const writeMode = args.includes("--write");
const checkMode = args.includes("--check");
const validateMode = args.includes("--validate");

function fail(message) {
  console.error(`ERROR: ${message}`);
  process.exit(1);
}

if (!manifestArg || [writeMode, checkMode, validateMode].filter(Boolean).length !== 1) {
  fail("使い方: node scripts/release-record.js releases/vNNN.json --write|--check|--validate");
}

const manifestPath = path.resolve(process.cwd(), manifestArg);
if (!fs.existsSync(manifestPath)) fail(`release記録がありません: ${manifestPath}`);

let record;
try {
  record = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
} catch (error) {
  fail(`release記録をJSONとして読めません: ${error.message}`);
}

const requiredStrings = ["date", "title", "summary"];
const requiredArrays = ["changedFiles", "intent", "changes", "uncertainties", "reviewFocus", "verification"];
const version = Number(record.version);

if (!Number.isInteger(version) || version < 164) fail("versionは164以上の整数にしてください");
if (path.basename(manifestPath) !== `v${version}.json`) {
  fail(`ファイル名はrecord.versionと一致するv${version}.jsonにしてください`);
}
for (const key of requiredStrings) {
  if (typeof record[key] !== "string" || !record[key].trim()) fail(`${key}は空でない文字列にしてください`);
}
for (const key of requiredArrays) {
  if (!Array.isArray(record[key]) || !record[key].length || record[key].some((item) => typeof item !== "string" || !item.trim())) {
    fail(`${key}は空でない文字列配列にしてください`);
  }
}
if (record.knownLimitations !== undefined && (
  !Array.isArray(record.knownLimitations)
  || record.knownLimitations.some((item) => typeof item !== "string" || !item.trim())
)) {
  fail("knownLimitationsは文字列配列にしてください");
}
if (!/^\d{4}-\d{2}-\d{2}$/.test(record.date)) fail("dateはYYYY-MM-DD形式にしてください");
if (validateMode) {
  console.log(`PASS: v${version} release記録schema`);
  process.exit(0);
}

const list = (items) => items.map((item) => `- ${item.trim()}`).join("\n");
const nestedList = (items) => items.map((item) => `  - ${item.trim()}`).join("\n");
const generatedNotice = "<!-- generated by scripts/release-record.js; edit releases/vNNN.json instead -->";
const changesText = `${generatedNotice}
# CHANGES v${version}: ${record.title.trim()}

## 概要

${record.summary.trim()}

## 変更ファイル

${list(record.changedFiles)}

## 変更内容

${list(record.changes)}

## 変更意図

${list(record.intent)}

## 検証

${list(record.verification)}

## 既知の制約・保留

${list(record.knownLimitations?.length ? record.knownLimitations : ["なし"])}
`;

const startMarker = `<!-- release-record:v${version}:start -->`;
const endMarker = `<!-- release-record:v${version}:end -->`;
const handoffBlock = `${startMarker}
## ${record.date} / v${version}
- 変更ファイル:
${nestedList(record.changedFiles)}
- 変更意図:
${nestedList(record.intent)}
- 自信がない箇所:
${nestedList(record.uncertainties)}
- レビュー希望観点:
${nestedList(record.reviewFocus)}
- 検証:
${nestedList(record.verification)}
${endMarker}`;

const changesPath = process.env.RELEASE_CHANGES_PATH
  ? path.resolve(process.env.RELEASE_CHANGES_PATH)
  : path.join(repoRoot, `CHANGES_v${version}.md`);
const handoffPath = process.env.RELEASE_HANDOFF_PATH
  ? path.resolve(process.env.RELEASE_HANDOFF_PATH)
  : path.resolve(repoRoot, "..", "taskchute-notes", "handoff.md");

if (!fs.existsSync(handoffPath)) fail(`handoff.mdがありません: ${handoffPath}`);
const currentHandoff = fs.readFileSync(handoffPath, "utf8");
if (!currentHandoff.includes("# Handoff Log")) fail("handoff.mdに '# Handoff Log' がありません");

const markerPattern = new RegExp(
  `${startMarker.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${endMarker.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`,
  "g"
);
const markerMatches = currentHandoff.match(markerPattern) || [];
if (markerMatches.length > 1) fail(`handoff.mdにv${version}の生成ブロックが複数あります`);
if (!markerMatches.length && new RegExp(`^## .+ / v${version}\\s*$`, "m").test(currentHandoff)) {
  fail(`handoff.mdに手書きのv${version}記録があります。重複防止のため自動生成できません`);
}

const nextHandoff = markerMatches.length
  ? currentHandoff.replace(markerPattern, handoffBlock)
  : `${currentHandoff.trimEnd()}\n\n${handoffBlock}\n`;

if (checkMode) {
  const currentChanges = fs.existsSync(changesPath) ? fs.readFileSync(changesPath, "utf8") : "";
  const changesOk = currentChanges === changesText;
  const handoffOk = currentHandoff.includes(handoffBlock);
  if (!changesOk || !handoffOk) {
    console.error(`OUTDATED: CHANGES=${changesOk ? "OK" : "NG"} handoff=${handoffOk ? "OK" : "NG"}`);
    process.exit(1);
  }
  console.log(`PASS: v${version}のCHANGES/handoffはrelease記録と一致しています`);
  process.exit(0);
}

fs.writeFileSync(changesPath, changesText, "utf8");
fs.writeFileSync(handoffPath, nextHandoff, "utf8");
console.log(`WROTE: ${changesPath}`);
console.log(`WROTE: ${handoffPath}`);
